### ISSUE TITLE
Adding the keylistener through WPM doesn't reflect that it's been installed even though it is.

### ISSUE THREAD

**Issue by tuanway** [Servoy/svyKeyListener#1]
![keylistner](https://user-images.githubusercontent.com/7150474/38905264-2d93d680-4275-11e8-9984-4e3c75f4254e.PNG)

**Comment by jcompagner** [comment]
my feeling is that this is because of the name is not everywhere the same
"svykeylistener" in the package.json stuff (and in the index) but the manifest had "keylistener"

i changed that now, but we need a new release first to test that (also changed the manifest to "svykeylistener"

**Comment by jcompagner** [comment]
yes that is it.
If i install it, then in the zip package that is installed locally i change the name in the manifest to "svykeylistener" then restart servoy and it is showing up just fine in the wpm.
